server:
  port: 8802
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: tipjs
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_name: "./storages/logs/dex.xxx.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
